config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboard#index'

  # get 'react', to: 'react#index'
  get 'myson', to: 'react#index'
  get '*react', to: 'react#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    render 'dashboard/index'
  end
end

app/controllers/react_controller.rb
class ReactController < ApplicationController
  skip_before_action :verify_authenticity_token
  layout 'react'
  def index
    render 'react/index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/react_helper.rb
module ReactHelper
end

app/views/dashboard/index.haml
%h2 Hello, World
%h3 this is an example of rails routing in index
= link_to 'react component', myson_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrxReact</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/react.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>REACT PRX CONTROLLER</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="/css/main.css">
  </head>

  <body>
    <%= yield %>
    <script type="text/javascript" src="/js/main.js"></script>
  </body>
</html>

app/views/react/index.haml
%h2 This is the React component with a router
= link_to 'Dashboard', '/'
.div#react-mount